# Generated by Django 5.1.4 on 2024-12-12 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_course_description"),
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payed_lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="courses.lesson",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="pay_date",
            field=models.DateField(verbose_name="дата оплаты"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payed_course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="courses.course",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payed_money",
            field=models.PositiveIntegerField(verbose_name="сумма оплаты"),
        ),
    ]
