# Generated by Django 5.1.4 on 2024-12-16 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_payment_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"verbose_name": "Платеж", "verbose_name_plural": "Платежи"},
        ),
    ]
